### ISSUE TITLE
✨ 左のカラムに跳ぶボタンにカラム名が表示されてたりするとわかりやすい

### ISSUE THREAD

**Issue by ShotaroKataoka** [yamamoto-yuta/slack-deck#109]
![image](https://user-images.githubusercontent.com/42331656/147015237-4f62e779-bcc1-454f-a65d-b5411831c749.png)

ここ

**Comment by yamamoto-yuta** [comment]
実はマウスホバーで出るようになってるんですけど、それだと分かりづらいですかね？
![image](https://user-images.githubusercontent.com/55144709/147383330-2b2ca232-0bd5-48a1-9e7b-a433ea1bedee.png)

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
気づかんかった
それならいいか

**Comment by yamamoto-yuta** [comment]
一旦closeしますね
