### ISSUE TITLE
クリップボードのURLでカラムを生成する

### ISSUE THREAD

**Issue by ShotaroKataoka** [yamamoto-yuta/slack-deck#124]
クリップボードのURLのカラムを生成するボタンが欲しい
ワンクリックでカラムが横に開くと便利

あと，カラムごとの上部とかにURLコピーとURLペーストボタンがあるといいかも
新規カラムじゃなくて既存カラムでURLを開きたいこともあると思うので

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
実装したのでcloseします。

画像赤丸左：クリップボードのURLでカラムを追加する
画像赤丸右：そのカラムでクリップボードのURLを開く

![image](https://user-images.githubusercontent.com/55144709/163715994-fbf37c89-2412-4b40-91a8-b3a01b6a821e.png)

SlackのURL以外がクリップボードにあった場合は↓のような表示が出ます。

![image](https://user-images.githubusercontent.com/55144709/163716067-67abe4e3-9fb1-41ab-b4f0-322849b96d91.png)

**Comment by yamamoto-yuta** [comment]
参考記事：
- [Navigator.clipboard - Web API | MDN](https://developer.mozilla.org/ja/docs/Web/API/Navigator/clipboard)
